image: alpine:3.9

variables:
  # Software versions for command line tools
  KUBERNETES_VERSION: 1.15.0
  HELM_VERSION: 2.14.2

  # Project information
  PROJECT_NAME: drupalwxt/site-wxt

  # Docker
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: 'tcp://localhost:2375'
  DOCKER_TLS_CERTDIR: ''

stages:
  - build
  - test
  - deploy
  - cleanup

before_script:
  - command -v git && git config --global credential.helper store
  # - echo https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.example.ca > ~/.git-credentials
  - source .gitlab-ci/env.sh
  - source .gitlab-ci/common.sh

build:
  stage: build
  image: sylus/gitlab-ci
  services:
     - docker:stable-dind
  script:
    - .gitlab-ci/build.sh

# test:
#   stage: test
#   image: sylus/gitlab-ci
#   services:
#      - docker:stable-dind
#   script:
#     - .gitlab-ci/test.sh
